name: Test and Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - name: Run tests
        run: npm test
  publish:
    if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - name: Package Win-x64 extension
        run: npm run package-win-x64
      - name: Publish Win-x64 extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          registryUrl: https://marketplace.visualstudio.com
          pat: ${{ secrets.NEVOD_VS_MARKETPLACE_TOKEN }}
          extensionFile: build/nevod-vscode-extension-win-x64.vsix
      - name: Package Darwin-x64 extension
        run: npm run package-darwin-x64
      - name: Publish Darwin-x64 extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          registryUrl: https://marketplace.visualstudio.com
          pat: ${{ secrets.NEVOD_VS_MARKETPLACE_TOKEN }}
          extensionFile: build/nevod-vscode-extension-darwin-x64.vsix
      - name: Package Linux-x64 extension
        run: npm run package-linux-x64
      - name: Publish Linux-x64 extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          registryUrl: https://marketplace.visualstudio.com
          pat: ${{ secrets.NEVOD_VS_MARKETPLACE_TOKEN }}
          extensionFile: build/nevod-vscode-extension-linux-x64.vsix
